"""add post and comment is_active

Revision ID: 05a352a6d943
Revises: 3e71f5e40b50
Create Date: 2017-05-21 23:44:04.424000

"""

# revision identifiers, used by Alembic.
revision = '05a352a6d943'
down_revision = '3e71f5e40b50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('is_active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_active')
    op.drop_column('comments', 'is_active')
    ### end Alembic commands ###
