"""user_pic

Revision ID: 3e71f5e40b50
Revises: d2933aa6ace4
Create Date: 2016-10-31 14:59:54.230000

"""

# revision identifiers, used by Alembic.
revision = '3e71f5e40b50'
down_revision = 'd2933aa6ace4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('user_pic', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'user_pic')
    ### end Alembic commands ###
