"""head_pic

Revision ID: 5a4ae9c8d06b
Revises: 79145efb2f4b
Create Date: 2016-10-28 11:24:21.969000

"""

# revision identifiers, used by Alembic.
revision = '5a4ae9c8d06b'
down_revision = '79145efb2f4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('head_pic', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'head_pic')
    ### end Alembic commands ###
