"""tag

Revision ID: 748abb45601e
Revises: fcb1925db09d
Create Date: 2016-10-25 16:56:04.746000

"""

# revision identifiers, used by Alembic.
revision = '748abb45601e'
down_revision = 'fcb1925db09d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tag', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tag')
    ### end Alembic commands ###
