"""comment conection

Revision ID: 79145efb2f4b
Revises: 748abb45601e
Create Date: 2016-10-27 19:49:01.558000

"""

# revision identifiers, used by Alembic.
revision = '79145efb2f4b'
down_revision = '748abb45601e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('connection', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'connection')
    ### end Alembic commands ###
