"""post pic

Revision ID: d2933aa6ace4
Revises: 5a4ae9c8d06b
Create Date: 2016-10-28 18:16:17.292000

"""

# revision identifiers, used by Alembic.
revision = 'd2933aa6ace4'
down_revision = '5a4ae9c8d06b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_pic', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_pic')
    ### end Alembic commands ###
