"""abstract

Revision ID: fcb1925db09d
Revises: None
Create Date: 2016-10-25 10:59:48.327000

"""

# revision identifiers, used by Alembic.
revision = 'fcb1925db09d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('abstract', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'abstract')
    ### end Alembic commands ###
